files:
  - 
    source: '/**/*.*'
<<<<<<< HEAD
    translation: '/**/%locale%/%original_file_name%'
=======
    translation: '/%two_letters_code%/**/%original_file_name%'
>>>>>>> 0ff10f767e7917350316d3f7ef5bc229575c6042
